### ISSUE TITLE
Add icon and group name to each event in Events list

### ISSUE THREAD

**Issue by egillespie** [brightdigit/lansingcodes-apple#4]
As a new attendee, it would be helpful to see both the group name for each event on the Events page of the Lansing Codes app to help me find groups that I may be interested in joining. In addition, showing the group name also makes the list more accessible to people who use the Speak Screen feature of iOS.

As a regular attendee who is familiar with the Lansing Codes group icons, it would be helpful to see the group icon for each event on the Events page so I can quickly skim all the upcoming events for the ones most relevant to my groups' interests.

**Possible solution**

Similar to the mobile view of the Lansing Codes website, show the group icon on the left side of each event. Each event would then have three lines of text:

1. Event name
2. Group name
3. Date and location

**Comment by leogdion** [comment]
This has been added to beta 5
