### ISSUE TITLE
Add content to About page

### ISSUE THREAD

**Issue by egillespie** [brightdigit/lansingcodes-apple#7]
As a user of the Lansing Codes app, I would like to see who maintains the app and Lansing Codes website on the About page. In addition, it would be helpful to see links to the Lansing Codes Slack team and/or inviter as well as the appropriate place to report issues or ask for feature requests in the app.

**Comment by leogdion** [comment]
![Simulator Screen Shot - iPhone 11 - 2019-12-11 at 14 10 25](https://user-images.githubusercontent.com/1036388/70652107-0b292b00-1c20-11ea-9644-5525c94924d6.png)
Adding clicking able links

**Comment by leogdion** [comment]
This has been added to beta 5
